name: Actions Workflow

on: [push]

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Javascript action
        id: first
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: José
      - name: After greeting
        run: echo "${{ steps.first.outputs.time }}"

      - name: Does checkout
        uses: actions/checkout@v1
      - name: Lists folder
        run: ls -altr
